# Generated by Django 3.0 on 2020-01-24 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eventname', models.CharField(max_length=200, null=True)),
                ('desc', models.TextField(max_length=2000)),
                ('Location', models.CharField(max_length=200, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Image', models.ImageField(null=True, upload_to='')),
                ('Rating', models.PositiveIntegerField(null=True)),
                ('Review', models.TextField(max_length=2000, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
