# Generated by Django 3.0 on 2020-01-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0002_auto_20200128_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='Date',
            field=models.DateTimeField(null=True),
        ),
    ]
