# Generated by Django 3.0 on 2020-02-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0003_auto_20200128_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='desc',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
