# Generated by Django 3.0 on 2020-03-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0004_auto_20200221_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
