# Generated by Django 2.2.6 on 2020-03-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0006_remove_diary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
