# Generated by Django 2.2.6 on 2020-03-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0007_diary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='Image',
            field=models.ImageField(null=True, upload_to='event_image'),
        ),
    ]
