# Generated by Django 2.2.6 on 2020-05-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0010_auto_20200324_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='Image',
            field=models.ImageField(default='Mainapp/static/Mainapp/images/sakura.jpg', upload_to='Mainapp/static/Mainapp/images'),
        ),
    ]
