# Generated by Django 2.2.6 on 2020-05-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0011_auto_20200507_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='Image',
            field=models.ImageField(default='static/Mainapp/images/static/sakura.jpg', upload_to='static/Mainapp/images/static'),
        ),
    ]
