# Generated by Django 2.2.6 on 2020-05-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0014_auto_20200507_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='Image',
            field=models.ImageField(default='static/Mainapp/images/sakura.jpg', upload_to=''),
        ),
    ]
